import React, { useState } from "react";
import {
  CaseDataset,
  CrimeNetworkNode,
  CrimeNetworkLink,
  SuspiciousPattern,
  SyndicateCommunity,
  CourtDossier,
} from "../types";
import { generateDossierWithGemini } from "../services/nlpExtractor";
import {
  FileText,
  X,
  Printer,
  Copy,
  Download,
  ShieldCheck,
  ShieldAlert,
  Crown,
  Check,
  Sparkles,
  AlertTriangle,
} from "lucide-react";

interface DossierModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentCase: CaseDataset;
  nodes: CrimeNetworkNode[];
  links: CrimeNetworkLink[];
  patterns: SuspiciousPattern[];
  communities: SyndicateCommunity[];
}

export const DossierModal: React.FC<DossierModalProps> = ({
  isOpen,
  onClose,
  currentCase,
  nodes,
  links,
  patterns,
  communities,
}) => {
  const [dossier, setDossier] = useState<CourtDossier | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleGenerateDossier = async () => {
    setIsGenerating(true);
    try {
      const generated = await generateDossierWithGemini(
        currentCase.codeName,
        nodes,
        links,
        patterns,
        communities
      );
      setDossier(generated);
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  // Fallback / Initial default template if not generated by AI yet
  const displayDossier: CourtDossier = dossier || {
    caseTitle: `${currentCase.codeName} - ${currentCase.name}`,
    caseNumber: currentCase.id,
    generatedAt: new Date().toISOString(),
    classification: "CONFIDENTIAL // FOR LAW ENFORCEMENT & JUDICIAL PROSECUTION ONLY",
    executiveSummary: currentCase.description,
    keySuspects: nodes
      .filter((n) => n.isKingpinCandidate || n.riskScore >= 75)
      .map((n) => ({
        id: n.id,
        name: n.label,
        role: n.role || n.type,
        riskScore: n.riskScore,
        centralityMetric: `Betweenness: ${n.betweenness || "0.000"}, Degree: ${n.degree || 0}`,
        knownAliases: n.aliases || [],
        allegedActs: n.details?.notes || "Identified key coordinator across communication and funding trails.",
      })),
    subSyndicateBreakdown: communities.map((c) => ({
      communityName: c.name,
      purpose: c.role,
      memberCount: c.nodeIds.length,
      topLeader: nodes.find((n) => n.id === c.keyLeaderId)?.label || "Undisclosed",
    })),
    suspiciousPatternsDetected: patterns.map((p) => ({
      patternTitle: p.title,
      severity: p.severity,
      evidenceSummary: p.description,
      actionableLead: p.actionableLead,
    })),
    actionableNextSteps: [
      "Issue Look-Out Circulars (LOC) at all international air terminals for Kingpin candidates.",
      "Execute Section 102 CrPC freeze directives on identified mule bank accounts.",
      "Requisition Section 91 CrPC call detail records and GPRS logs for flagged burner IMEIs.",
      "Issue non-bailable search warrants for identified safehouses.",
    ],
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = `
# CONFIDENTIAL // LAW ENFORCEMENT INTELLIGENCE DOSSIER
**CASE REF:** ${displayDossier.caseTitle} (${displayDossier.caseNumber})
**DATE:** ${new Date(displayDossier.generatedAt).toLocaleString()}
**CLASSIFICATION:** ${displayDossier.classification}

---

## 1. EXECUTIVE SUMMARY
${displayDossier.executiveSummary}

## 2. KEY SUSPECTS & HIERARCHICAL PROFILES
${displayDossier.keySuspects
  .map(
    (s) =>
      `### ${s.name} (${s.role}) - Risk: ${s.riskScore}/100\n- **Metrics:** ${s.centralityMetric}\n- **Aliases:** ${s.knownAliases.join(", ") || "None"}\n- **Allegations:** ${s.allegedActs}`
  )
  .join("\n\n")}

## 3. SUSPICIOUS PATTERN EVIDENCE
${displayDossier.suspiciousPatternsDetected
  .map((p) => `- **[${p.severity}] ${p.patternTitle}:** ${p.evidenceSummary}\n  *Lead:* ${p.actionableLead}`)
  .join("\n\n")}

## 4. ACTIONABLE PROSECUTION & TACTICAL STEPS
${displayDossier.actionableNextSteps.map((step, idx) => `${idx + 1}. ${step}`).join("\n")}
    `.trim();

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(displayDossier, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `DOSSIER_${currentCase.codeName}_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 sm:p-6 overflow-y-auto animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Top Header */}
        <div className="p-4 sm:p-5 border-b border-slate-800 bg-slate-950 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-amber-500/10 rounded-xl text-amber-400 border border-amber-500/20">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/30">
                  {displayDossier.classification}
                </span>
              </div>
              <h2 className="text-sm sm:text-base font-bold text-slate-100 mt-1">
                Court-Ready Intelligence Dossier & Chargesheet Annexure
              </h2>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleGenerateDossier}
              disabled={isGenerating}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white rounded-lg text-xs font-bold transition-colors shadow"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>{isGenerating ? "Synthesizing with AI..." : "Re-Synthesize via Gemini"}</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-200 hover:bg-slate-800 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Dossier Document Content Area */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-8 bg-slate-950/60 font-sans space-y-6 print:bg-white print:text-black">
          {/* Document Masthead */}
          <div className="border-b-2 border-slate-700 pb-4 text-center">
            <div className="text-[11px] font-mono uppercase tracking-widest text-amber-400 font-bold mb-1">
              CENTRAL INTELLIGENCE & LAW ENFORCEMENT GRAPH INTELLIGENCE DIVISION
            </div>
            <h1 className="text-xl sm:text-2xl font-black text-slate-100 tracking-tight">
              {displayDossier.caseTitle}
            </h1>
            <div className="flex items-center justify-center gap-4 text-xs text-slate-400 mt-2 font-mono">
              <span>CASE ID: {displayDossier.caseNumber}</span>
              <span>•</span>
              <span>GENERATED: {new Date(displayDossier.generatedAt).toLocaleDateString()}</span>
              <span>•</span>
              <span className="text-rose-400 font-bold">SEC 65B EVIDENCE CERTIFIED</span>
            </div>
          </div>

          {/* 1. Executive Summary */}
          <div>
            <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-2">
              1. Executive Case Summary
            </h3>
            <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl text-xs text-slate-200 leading-relaxed">
              {displayDossier.executiveSummary}
            </div>
          </div>

          {/* 2. Key Suspects & Kingpin Hierarchy */}
          <div>
            <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-2">
              2. Primary Suspect Profiles & Graph Centrality
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {displayDossier.keySuspects.map((s) => (
                <div
                  key={s.id}
                  className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-2 text-xs"
                >
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-100 text-sm flex items-center gap-1.5">
                      <Crown className="w-4 h-4 text-amber-400" />
                      {s.name}
                    </span>
                    <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-500/20 text-amber-300">
                      RISK: {s.riskScore}/100
                    </span>
                  </div>
                  <span className="text-[11px] text-slate-400 block">{s.role}</span>
                  <div className="text-[11px] font-mono text-slate-400 bg-slate-950 p-2 rounded border border-slate-800/80">
                    {s.centralityMetric}
                  </div>
                  <p className="text-[11px] text-slate-300">{s.allegedActs}</p>
                </div>
              ))}
            </div>
          </div>

          {/* 3. Suspicious Algorithmic Patterns */}
          <div>
            <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-2">
              3. Automated Pattern Inferences & Money Trail Evidence
            </h3>
            <div className="space-y-3">
              {displayDossier.suspiciousPatternsDetected.map((p, idx) => (
                <div
                  key={idx}
                  className="p-3.5 bg-slate-900 border border-slate-800 rounded-xl text-xs space-y-1.5"
                >
                  <div className="flex items-center justify-between">
                    <strong className="text-slate-100 font-bold flex items-center gap-1.5">
                      <AlertTriangle className="w-3.5 h-3.5 text-rose-400" />
                      {p.patternTitle}
                    </strong>
                    <span className="text-[10px] font-mono font-bold text-rose-400">
                      [{p.severity}]
                    </span>
                  </div>
                  <p className="text-slate-300 text-[11px] leading-relaxed">{p.evidenceSummary}</p>
                  <p className="text-[11px] text-amber-300 bg-amber-500/10 p-2 rounded border border-amber-500/20 font-medium">
                    <strong>Tactical Action:</strong> {p.actionableLead}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* 4. Actionable Next Steps */}
          <div>
            <h3 className="text-xs font-bold text-amber-400 uppercase tracking-wider mb-2">
              4. Immediate Tactical & Legal Directives
            </h3>
            <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl text-xs space-y-2">
              {displayDossier.actionableNextSteps.map((step, idx) => (
                <div key={idx} className="flex items-start gap-2 text-slate-200">
                  <span className="text-amber-400 font-bold font-mono">{idx + 1}.</span>
                  <span>{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Modal Footer Controls */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg border border-slate-700 transition-colors"
            >
              <Printer className="w-4 h-4" />
              <span>Print Dossier</span>
            </button>

            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg border border-slate-700 transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? "Copied to Clipboard!" : "Copy Markdown"}</span>
            </button>

            <button
              onClick={handleDownloadJSON}
              className="flex items-center gap-1.5 px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg border border-slate-700 transition-colors"
            >
              <Download className="w-4 h-4" />
              <span>Export JSON Annexure</span>
            </button>
          </div>

          <button
            onClick={onClose}
            className="px-4 py-2 bg-amber-500 hover:bg-amber-600 text-slate-950 font-bold text-xs rounded-lg transition-colors shadow"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
